### ISSUE TITLE
mplement Hover Effect boxes for Affordances

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/MIA#4]
We need to implement a hover effect for links representing affordances on the Marine Info Affordances project pages. The hover effect should be styled similarly to the hover boxes on the vliz.atlassian.net pages, including the following features:
- Displaying the Marine Info logo in front of the link.
- Changing the border color on hover.

#### Acceptance Criteria:

- Add the Marine Info logo in front of each affordance link.
- Implement a CSS hover effect that changes the border color of the link box.
- Ensure the hover effect is consistent with the styling on vliz.atlassian.net pages.

```css
      .affordance-link {
          display: flex;
          align-items: center;
          padding: 5px;
          border: 1px solid transparent;
          transition: border-color 0.3s;
      }

        .affordance-link img {
            margin-right: 8px;
            width: 20px;
            height: 20px;
        }

        .affordance-link:hover {
            border-color: #007BFF; /* Change to desired hover border color */
        }
```
